server:
  port: ${SERVER_PORT:8841}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    baseline-on-migrate: true
    placeholders:
      schema: ${app.postgres.schema}

app:
  social-benefits: ${SOCIAL_BENEFITS_ENABLE:true}
  standard-category-booking-timeout: ${STANDARD_CATEGORY_BOOKING_TIMEOUT:2}
  occupancy-timeout: ${OCCUPANCY_TIMEOUT:1}
  occupancy-min-rate: ${OCCUPANCY_MIN_RATE:2}
  occupancy-max-rate: ${OCCUPANCY_MAX_RATE:5}
  occupancy-checker-cron: "0 * * ? * *" # every minute
  social-one-discount-percentage: ${SOCIAL_ONE_DISCOUNT_PERCENTAGE:1}
  social-two-discount-percentage: ${SOCIAL_TWO_DISCOUNT_PERCENTAGE:2}
  social-three-discount-percentage: ${SOCIAL_THREE_DISCOUNT_PERCENTAGE:3}
  postgres:
    driver-class-name: ${POSTGRES_DRIVER:org.postgresql.Driver}
    jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/tbs}
    username: ${POSTGRES_USER:tbs}
    password: ${POSTGRES_PASSWORD:tbs}
    schema: ${POSTGRES_DB:public}
    connection-timeout: 20000
    connection-init-sql: ALTER ROLE ${POSTGRES_USER:tbs} SET search_path TO ${POSTGRES_DB:public}
    connection-test-query: SELECT 1